"""
Audit Logger — Immutable append-only audit trail for all generated artifacts.

Every artifact generated by the deception engine is logged with:
timestamp, session_id, artifact_type, content hash, and policy result.
"""

from __future__ import annotations

import hashlib
import logging
from datetime import datetime, timezone

from app.models.safety_models import AuditEntry, PolicyResult

logger = logging.getLogger(__name__)


class AuditLogger:
    """Immutable append-only audit log for generated artifacts."""

    def __init__(self) -> None:
        self._log: list[AuditEntry] = []

    def log_generation(
        self,
        session_id: str,
        artifact_type: str,
        artifact_id: str,
        content_bytes: bytes | None = None,
        user_id: str = "anonymous",
        scammer_id: str = "unknown",
        policy_result: PolicyResult | None = None,
    ) -> AuditEntry:
        """Log an artifact generation event."""
        content_hash = ""
        if content_bytes:
            content_hash = hashlib.sha256(content_bytes).hexdigest()

        entry = AuditEntry(
            timestamp=datetime.now(timezone.utc),
            session_id=session_id,
            artifact_type=artifact_type,
            artifact_id=artifact_id,
            content_hash=content_hash,
            user_id_hash=hashlib.sha256(user_id.encode()).hexdigest()[:16],
            scammer_id_hash=hashlib.sha256(scammer_id.encode()).hexdigest()[:16],
            policy_result=policy_result or PolicyResult(),
        )

        self._log.append(entry)

        logger.info(
            "AUDIT: artifact=%s type=%s session=%s hash=%s",
            artifact_id, artifact_type, session_id, content_hash[:16] if content_hash else "N/A",
        )

        return entry

    def get_log(
        self,
        session_id: str | None = None,
        limit: int = 100,
    ) -> list[AuditEntry]:
        """Retrieve audit log entries, optionally filtered by session."""
        entries = self._log
        if session_id:
            entries = [e for e in entries if e.session_id == session_id]
        return entries[-limit:]

    def get_count(self) -> int:
        """Total number of audit entries."""
        return len(self._log)

    def purge_older_than_days(self, days: int = 90) -> int:
        """Auto-purge entries older than retention period."""
        cutoff = datetime.now(timezone.utc)
        from datetime import timedelta
        cutoff = cutoff - timedelta(days=days)

        before = len(self._log)
        self._log = [e for e in self._log if e.timestamp > cutoff]
        purged = before - len(self._log)

        if purged > 0:
            logger.info("Purged %d audit entries older than %d days", purged, days)

        return purged
